### ISSUE TITLE
No story output when testing sub-packages.

### ISSUE THREAD

**Issue by thedodd** [franela/goblin#51]
When executing `go test` against multiple packages, I am not getting any output other than the standard `go test` output. None of the `Describe` & `It` descriptions are being output to the terminal.

```bash
$ go test github.com/thedodd/<pkg> github.com/thedodd/<pkg>/lib
?   github.com/thedodd/<pkg>      [no test files]
ok  github.com/thedodd/<pkg>/lib  0.195s
```

**Comment by marcosnils** [comment]
@thedodd in that case you need to run `go test -v`

**Comment by thedodd** [comment]
@marcosnils awesome. That did the trick. Thanks for the very quick response.
