### ISSUE TITLE
Entire output for - go test <package>

### ISSUE THREAD

**Issue by ameykpatil** [franela/goblin#54]
When I run `go test`
`goblin` shows a nice output (along with all the passing tests)

But when there are multiple packages, I need to run `go test <package-1> <package-2>`
In this case, `goblin` does not show entire output & just shows
`ok  	github.com/ameykpatil/<package-name>	22.832s`

I don't even come to know how many total tests were there. 

How can I get entire output in case of `go test <package-1> <package-2>`?
(I am a beginner in `go` world, I am not really sure if this is an issue with `goblin` or something else)

**Comment by marcosnils** [comment]
check https://github.com/franela/goblin/issues/51
