### ISSUE TITLE
Dep ensures invalid version.

### ISSUE THREAD

**Issue by Lucassith** [franela/goblin#69]
Hello

adding goblin via dep cli `dep ensure -add github.com/franela/goblin` will install 0.0.1 tag version. One can change it by setting proper branch in Gopkg.toml to:
```
[[constraint]]
  name = "github.com/franela/goblin"
  branch = "master"
```
but it needs some thinking before finding out what's wrong.

**Comment by marcosnils** [comment]
Just released v0.0.2 which should have the same thing as master. We're not actively working on this project ATM, but PR's are always welcome. 

Thx for supporting the project.
