### ISSUE TITLE
Regexp test selector does not seem to work.

### ISSUE THREAD

**Issue by snobb** [franela/goblin#74]
I cannot see the regexp flag -goblin.run working unless I comment out the `flag.Parsed()` check in the Goblin constructor. In my tests it seems to always be `true` even though I do not see where else the `flag.Parse()` is called.
```
func Goblin(t *testing.T, arguments ...string) *G {
	// if !flag.Parsed() {
	parseFlags()
	// }
```
Removing the check seems to work well though.

The command I run is as follows:
```
$ go test ./pkg/... -v -goblin.run="regexp"
```
OR
```
$ go test ./pkg/... -v -args -goblin.run="regexp"
```

EDIT: I am using go1.11

**Comment by marcosnils** [comment]
Interesting. Maybe something changed in the latest versions of Go which changed this behavior. It's also strange that you changed the code and tests are still passing. I'll check it out in the weekend.

**Comment by snobb** [comment]
Any update on this? Thanks.

**Comment by ahmedhosnycs** [comment]
I've migrated from go1.9 to go1.13 and since then I've the same issue. Would appreciate any input or workaround regarding this issue

**Comment by sockol** [comment]
This fixed the issue for me, but lmk if you think there's a better solution @marcosnils
